services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FelixNagel\Beautyofcode\:
    resource: '../Classes/*'

  # Dependency injection
  FelixNagel\Beautyofcode\Service\SettingsService:
    public: true

  FelixNagel\Beautyofcode\Domain\Model\Flexform:
    public: true

  # Interface implementations
  FelixNagel\Beautyofcode\Highlighter\ConfigurationInterface:
    alias: FelixNagel\Beautyofcode\Highlighter\Configuration
    public: true
