# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2020
  project: beautyofcode
  version: 4.1.0
  release: 4.1.0
...
