name: tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        php-versions: [7.2, 7.3, 7.4]
        typo3-versions: [9.5, 10.4]

    name: PHP ${{ matrix.php-versions }} with TYPO3 ${{ matrix.typo3-versions }}
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, mbstring, pdo_sqlite

      - name: Install composer dependencies
        run: composer require typo3/minimal "^${{ matrix.typo3-versions }}" --prefer-dist --no-progress --no-suggest

      - name: Run PHP lint
        run: composer run-script test-php-lint

      - name: Run PHPCS
        run: composer run-script test-php-cs-fixer

      - name: Run PHPMD
        run: composer run-script test-php-md

      - name: Run PHPUnit
        run: composer run-script test-phpunit
